### PR TITLE
Trying to save some more memory

### PR DESCRIPTION
**Pull request by muschellij2**
I have a very large data set, so I'm trying to get it to run on a laptop, but I'm running into memory issues with 16Gb, so trying to cut the copies of the large vectors.

### CODE REVIEW

**Comment by qutang** [comment]
Which function did you call? The `mims_unit_from_files` should already handle any size of data file.

**Comment by muschellij2** [comment]
I'm using raw gt3x files read into R.  I can write them out to chunk, but
there is no chunk option or chunk function that's exposed from MIMSunit,
correct?

Best,
John

**Comment by qutang** [comment]
What function or package do you use the load gt3x file? We may consider including that into the package.

**Comment by muschellij2** [comment]
I was using `read.gt3x::read.gt3x` from https://github.com/THLfi/read.gt3x.  I was using this file `https://ndownloader.figshare.com/files/21855795` from https://figshare.com/articles/Raw_GT3X_Data_Duplicate/11916087

**Comment by qutang** [comment]
The package currently is not on CRAN, so I cannot include that as part of the package.

**Pull request merged**
